//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergoGlobalKalkulator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class energo_globalEntities : DbContext
    {
        public energo_globalEntities()
            : base("name=energo_globalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BrojFaza> BrojFazas { get; set; }
        public DbSet<Korak> Koraks { get; set; }
        public DbSet<Projekat> Projekats { get; set; }
        public DbSet<Projektant> Projektants { get; set; }
        public DbSet<StartMotora> StartMotoras { get; set; }
        public DbSet<TipPotrosaca> TipPotrosacas { get; set; }
        public DbSet<ProjekatKorakUkupno> ProjekatKorakUkupnoes { get; set; }
    }
}
