//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergoGlobalKalkulator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Projektant
    {
        public Projektant()
        {
            this.Projekats = new HashSet<Projekat>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Šifra { get; set; }
        public string Kompanija { get; set; }

         [Display(Name = "Broj telefona")]
        public string Broj_telefona { get; set; }
    
        public virtual ICollection<Projekat> Projekats { get; set; }
    }
}
