//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergoGlobalKalkulator.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


   
    public partial class Projekat
    {

         
        public Projekat()
        {
            this.Koraks = new HashSet<Korak>();
            this.ProjekatKorakUkupnoes = new HashSet<ProjekatKorakUkupno>();
        }

         [JsonIgnore]
         
        public int Id { get; set; }


     
     
        [Required(ErrorMessage = "Niste uneli naziv projekta")]
     
        [Display(Name = "Naziv projekta")]
       
        public string Naziv_projekta { get; set; }

        
       
        [Display(Name = "Datum izrade")]
        public string Datum_izrade { get; set; }


       
        public Nullable<int> IdProjektant { get; set; }


         
         
        [Display(Name = "Ime projektanta")]
        public string Ime_projektanta { get; set; }


       
        
        public virtual ICollection<Korak> Koraks { get; set; }

       
        
        public virtual Projektant Projektant { get; set; }


         [JsonIgnore]
        public virtual ICollection<ProjekatKorakUkupno> ProjekatKorakUkupnoes { get; set; }
    }
}
