//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergoGlobalKalkulator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjekatKorakUkupno
    {
        public int IdProjekat { get; set; }
        public int IdKorak { get; set; }
        public decimal StartA_Ukupno { get; set; }
        public decimal StartKVA_Ukupno { get; set; }
        public decimal StartKW_Ukupno { get; set; }
        public decimal RadKVA_Ukupno { get; set; }
        public decimal RadKW_Ukupno { get; set; }
        public decimal RadA_Ukupno { get; set; }
    
        public virtual Korak Korak { get; set; }
        public virtual Projekat Projekat { get; set; }
    }
}
